name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.15'

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Prepare deployment
        run: |
          echo "Preparing deployment for PHP project"

      - name: Deploy to Staging Server
        env:
          HOST: ${{ secrets.STAGING_SERVER_HOST }}
          USER: ${{ secrets.STAGING_SERVER_USER }}
          PASSWORD: ${{ secrets.STAGING_SERVER_SSH_PASSWORD }}
          PORT: ${{ secrets.STAGING_SERVER_SSH_PORT }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p "$PORT" $USER@$HOST << 'EOF'
            cd /sites/yadr.kraft.net.ua/
            git pull origin master
            composer install --no-interaction --pref
